baseURL = 'https://chenxu66.github.io/'
languageCode = 'en-us'
title = 'Theo Chen'
theme = ["hugo-embed-pdf-shortcode", 'hugo-digital-garden-theme']
copyright = "Xu Chen ©"
enableInlineShortcodes = true
[Params]
    Name = "Xu (Theo) Chen"
    description = "M.Eng in Financial Engineering @ Cornell"
    initials = "Theo"

    [[Params.Social]]
        name = "Github"
        link = "https://github.com/chenxu66?tab=repositories"
        icon = "fab fa-github"
    [[Params.Social]]
        name = "Instagram"
        link = "https://www.instagram.com/chenxu.1/"
        icon = "fab fa-instagram"
    [[Params.Social]]
        name = "LinkedIn"
        link = "https://www.linkedin.com/in/theo-xuchen/"
        icon = "fab fa-linkedin-in"

[menu]
    [[menu.main]]
        name = "Garden"
        url = "/garden/"
        weight = 1
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 2
    [[menu.main]]
        name = "Library"
        url = "/library/"
        weight = 3
    [[menu.main]]
        name = "Resume"
        url = "/resume/"
        weight = 4
        
[markup]
    defaultMarkdownHandler = 'goldmark'
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.extensions]
        definitionList = true
        footnote = true
        linkify = true
        strikethrough = true
        table = true
        taskList = true
        typographer = true
    [markup.highlight]
        # Choose from https://xyproto.github.io/splash/docs/all.html
        style = 'monokailight'